import os

class GCodeEngine:
    @staticmethod
    def generate_raster_gcode(image, output_path, pixel_size=0.1, feed_rate=1000, laser_power=100):
        """
        Generiše Raster G-Code (Scanline) za lasere.
        image: PIL Image (mora biti BW ili Dithered)
        pixel_size: Veličina jednog piksela u mm (npr. 0.1mm)
        feed_rate: Brzina (mm/min)
        laser_power: Snaga lasera (0-1000 ili 0-255 zavisno od mašine, ovde S-max)
        """
        # Konvertuj u BW za analizu
        img = image.convert("L")
        width, height = img.size
        pixels = img.load()

        gcode = []
        
        # --- HEADER ---
        gcode.append("; Generated by CypherLens v8.0")
        gcode.append(f"; Dimensions: {width*pixel_size:.1f}mm x {height*pixel_size:.1f}mm")
        gcode.append("G21 ; Units in mm")
        gcode.append("G90 ; Absolute positioning")
        gcode.append("M5  ; Laser OFF")
        gcode.append(f"G0 F{feed_rate} ; Travel Speed")
        gcode.append("G0 X0 Y0 ; Go to Origin")

        # --- RASTER SCANNING ---
        # Skeniramo liniju po liniju (Zig-Zag)
        print("Generating G-Code paths...")
        
        on_command = "M3" # Ili M4 za dinamičku snagu
        off_command = "M5"
        
        for y in range(height):
            # Y koordinata (u CNC svetu Y raste nagore, ali slike idu nadole)
            # Ovde pretpostavljamo da je (0,0) dole levo, pa invertujemo Y
            y_pos = (height - 1 - y) * pixel_size
            
            # Odredi smer (Zig-Zag)
            if y % 2 == 0:
                x_range = range(width)      # Levo -> Desno
            else:
                x_range = range(width-1, -1, -1) # Desno -> Levo

            current_laser_state = False # False = OFF, True = ON
            
            # Pomeri na početak linije
            start_x = x_range[0] * pixel_size
            gcode.append(f"G0 X{start_x:.3f} Y{y_pos:.3f}")
            
            for x in x_range:
                # Proveri boju piksela (0=Crno/LaserON, 255=Belo/LaserOFF)
                # Kod lasera, crno gori.
                pixel_val = pixels[x, y]
                should_burn = (pixel_val < 128) 
                
                if should_burn and not current_laser_state:
                    # Upali laser
                    gcode.append(f"{on_command} S{laser_power}")
                    gcode.append(f"G1 X{x*pixel_size:.3f} Y{y_pos:.3f} F{feed_rate}") # Cut move
                    current_laser_state = True
                    
                elif not should_burn and current_laser_state:
                    # Ugasi laser
                    gcode.append(off_command)
                    gcode.append(f"G0 X{x*pixel_size:.3f} Y{y_pos:.3f}") # Travel move
                    current_laser_state = False
                
                # Ako stanje ostaje isto, samo produžavamo liniju (optimizacija)
                if current_laser_state:
                     # Ažuriraj samo poslednju poziciju u nizu komandi ako je ista vrsta pokreta
                     # (Ovo je prosta verzija, piše svaku komandu. Za v9.0 radimo kompresiju koda)
                     gcode.append(f"G1 X{x*pixel_size:.3f}")
            
            # Kraj linije - ugasi laser
            gcode.append(off_command)

        # --- FOOTER ---
        gcode.append("G0 X0 Y0 ; Return home")
        gcode.append("M2 ; End program")

        # Snimanje fajla
        try:
            with open(output_path, "w") as f:
                f.write("\n".join(gcode))
            return True
        except Exception as e:
            print(f"GCode Save Error: {e}")
            return False