import os
# Sada ovo mora da radi jer fajl postoji
from backend.config_manager import ConfigManager

class GCodeEngine:
    @staticmethod
    def generate_raster_gcode(image, filepath):
        # 1. Učitaj podešavanja
        settings = ConfigManager.load_settings()
        
        feed_rate = settings.get("feed_rate", 1000)
        plunge_rate = settings.get("plunge_rate", 300)
        safe_z = settings.get("safe_z", 5.0)
        spindle_speed = settings.get("spindle_speed", 12000)
        max_depth = settings.get("cut_depth", 2.0)
        
        pixel_step = 0.2 
        
        gray_img = image.convert("L")
        width, height = gray_img.size
        pixels = gray_img.load()
        
        with open(filepath, "w") as f:
            f.write(f"(Generated by CypherLens)\n")
            f.write(f"G21 (Metric Units)\n")
            f.write(f"G90 (Absolute Positioning)\n")
            f.write(f"M3 S{spindle_speed} (Start Spindle)\n")
            f.write(f"G0 Z{safe_z} (Move to Safe Z)\n")
            f.write(f"G0 X0 Y0 (Go to Origin)\n")
            
            print("Generating G-Code paths...")
            
            for y in range(height):
                if y % 2 == 0:
                    x_range = range(width)
                else:
                    x_range = range(width - 1, -1, -1)
                
                for x in x_range:
                    real_x = x * pixel_step
                    real_y = (height - y) * pixel_step
                    
                    pixel_val = pixels[x, y]
                    z_depth = -1 * ((255 - pixel_val) / 255.0) * max_depth
                    
                    f.write(f"G1 X{real_x:.3f} Y{real_y:.3f} Z{z_depth:.3f} F{feed_rate}\n")
            
            f.write(f"G0 Z{safe_z} (Retract to Safe Z)\n")
            f.write(f"M5 (Stop Spindle)\n")
            f.write(f"G0 X0 Y0 (Return Home)\n")
            f.write(f"M30 (End Program)\n")
            
        print(f"G-Code saved to: {filepath}")
        return True